CREATE TABLE IF NOT EXISTS
`agentverse-scholar-75ucadbn96u.sec_bronze.sec_sub`
(
  adsh STRING,
  cik STRING,
  name STRING,
  sic STRING,
  countryba STRING,
  stprba STRING,
  cityba STRING,
  zipba STRING,
  bas1 STRING,
  bas2 STRING,
  baph STRING,
  countryma STRING,
  stprma STRING,
  cityma STRING,
  mas1 STRING,
  mas2 STRING,
  countryinc STRING,
  stprinc STRING,
  ein STRING,
  former STRING,
  changed STRING,
  afs STRING,
  wksi STRING,
  fye STRING,
  form STRING,
  period STRING,
  fy STRING,
  fp STRING,
  filed STRING,
  accepted STRING,
  prevrpt STRING,
  detail STRING,
  instance STRING,
  nciks STRING,
  aciks STRING,

  -- Pipeline metadata
  batch_id STRING,
  source_file STRING,
  ingested_at TIMESTAMP
);
